baseURL: https://kaiserfranz.cz
languageCode: cs-cz
defaultContentLanguage: cs
title: Kaiser Franz
disableKinds: ["taxonomy", "taxonomyTerm", "sitemap", "RSS"]

menu:
  main:
  - identifier: uvod
    name: Úvod
    url: /
    weight: 1
  - identifier: nas-pribeh
    name: Náš příběh
    url: /nas-pribeh/
    weight: 2
  - identifier: svatebni-catering
    name: Svatby
    url: /svatebni-catering/
    weight: 3
  - identifier: catering
    name: Catering
    url: /catering/
    weight: 4
  - identifier: kontakt
    name: Kontakt
    url: /kontakt/
    weight: 5
