backend:
  name: git-gateway
  branch: master

display_url: "https://kaiserfranz.cz"
logo_url: "https://kaiserfranz.cz/img/logo.svg"
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "sections"
    label: "Sections"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: {label: "Image", name: "image", widget: "string"}
      - label: "Náš příběh"
        name: "nas-pribeh"
        file: "content/nas-pribeh/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: {label: "Image", name: "image", widget: "string"}
      - label: "Catering"
        name: "catering"
        file: "content/catering/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Clients"
            name: "clients"
            widget: "list"
            required: false
            fields:
              - label: "Client"
                name: "client"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: {label: "Image", name: "image", widget: "string"}
      - label: "Kontakt"
        name: "kontakt"
        file: "content/kontakt/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: {label: "Image", name: "image", widget: "string"}
      - label: "Globals"
        name: "globals"
        file: "data/globals.yml"
        delete: false
        fields:
          - {label: "Contact phone", name: "contact_phone", widget: "string"}
          - {label: "Reservation phone", name: "reservation_phone", widget: "string"}
          - {label: "Opening times", name: "opening_times", widget: "string"}
