backend:
  name: git-gateway
  branch: master

display_url: "https://kaiserfranz.cz"
logo_url: "https://kaiserfranz.cz/img/logo.svg"
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "sections"
    label: "Sections"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Náš příběh"
        name: "nas-pribeh"
        file: "content/nas-pribeh/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Bistro"
        name: "bistro"
        file: "content/bistro/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Akce"
        name: "akce"
        file: "content/akce/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - label: "Event"
                name: "event"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Start date", name: "start_date", widget: "date", format: "YYYY-MM-DD"}
                  - {label: "End date", name: "end_date", widget: "date", format: "YYYY-MM-DD"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Catering"
        name: "catering"
        file: "content/catering/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Clients"
            name: "clients"
            widget: "list"
            required: false
            fields:
              - label: "Client"
                name: "client"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Kontakt"
        name: "kontakt"
        file: "content/kontakt/_index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Globals"
        name: "globals"
        file: "data/globals.yml"
        delete: false
        fields:
          - {label: "Contact phone", name: "contact_phone", widget: "string"}
          - {label: "Reservation phone", name: "reservation_phone", widget: "string"}
          - {label: "Opening times", name: "opening_times", widget: "string"}
